namespace DIP.AgenticExtraction.Poc.Models;

public enum JobStatus { Uploaded, Queued, Processing, Completed, Failed }

/// <summary>A polygon point (normalized 0-1 coordinates relative to page dimensions).</summary>
public record PolygonPoint(double X, double Y);

/// <summary>Bounding region — page number + polygon for where a value was found.</summary>
public record BoundingRegion
{
    public int PageNumber { get; init; }
    /// <summary>Polygon points (normalized 0-1). Typically 4 points for a rectangle.</summary>
    public List<PolygonPoint> Polygon { get; init; } = [];
}

public record ExtractionFieldResult
{
    public object? Value { get; init; }         // Typed: string, double, int
    public int Confidence { get; init; }        // 0-100
    public bool IsVerified { get; init; }       // True if VerificationAgent confirmed correct
    public string RawStr { get; init; } = "";   // Exact string as it appeared in document
    /// <summary>Where in the document this value was found (page + polygon).</summary>
    public List<BoundingRegion> BoundingRegions { get; init; } = [];
}

public record RequestedFieldResult
{
    public object? Value { get; init; }
    public int? Confidence { get; init; }       // null for generated fields
    public bool IsVerified { get; init; }
    public string Source { get; init; } = "";   // "extracted" or "generated"
    public string? RawStr { get; init; }         // Exact string as it appeared in document (extracted fields only)
    /// <summary>Where in the document this value was found (page + polygon).</summary>
    public List<BoundingRegion> BoundingRegions { get; init; } = [];
}

public record ExtractionJobResult
{
    public required string JobId { get; init; }
    public JobStatus Status { get; init; }
    /// <summary>List of entity instances extracted from the document (e.g., multiple invoices in one PDF).</summary>
    public List<InstanceResult> Instances { get; init; } = [];
    /// <summary>C# expressions generated by GPT-5 and executed by Roslyn for each generation field.</summary>
    public Dictionary<string, string> GenerationScripts { get; init; } = [];
    public ExtractionMetadata Metadata { get; init; } = new();
    public string? ErrorMessage { get; init; }
}

/// <summary>One extracted entity instance within a document.</summary>
public record InstanceResult
{
    public Dictionary<string, RequestedFieldResult> RequestedFields { get; init; } = [];
    public Dictionary<string, ExtractionFieldResult> Fields { get; init; } = [];
    public Dictionary<string, List<Dictionary<string, object?>>> TableFields { get; init; } = [];
    public Dictionary<string, object?> GeneratedFields { get; init; } = [];
    /// <summary>Page numbers (1-indexed) from which this instance's data was extracted.</summary>
    public List<int> SourcePages { get; init; } = [];
}

public record ExtractionMetadata
{
    public bool SchemaWasAutoGenerated { get; init; }
    public int LlmCallCount { get; init; }
    public int CorrectionIterations { get; init; }
    public long ProcessingTimeMs { get; init; }
    public int OcrPageCount { get; init; }
}
