namespace DIP.AgenticExtraction.Poc.Models;

public enum JobStatus { Uploaded, Queued, Processing, Completed, Failed }

public record ExtractionFieldResult
{
    public object? Value { get; init; }         // Typed: string, double, int
    public int Confidence { get; init; }        // 0-100
    public bool IsVerified { get; init; }       // True if VerificationAgent confirmed correct
    public string RawStr { get; init; } = "";   // Exact string as it appeared in document
}

public record ExtractionJobResult
{
    public required string JobId { get; init; }
    public JobStatus Status { get; init; }
    public Dictionary<string, object?> RequestedFields { get; init; } = [];
    public Dictionary<string, ExtractionFieldResult> Fields { get; init; } = [];
    public Dictionary<string, List<Dictionary<string, object?>>> TableFields { get; init; } = [];
    public Dictionary<string, object?> GeneratedFields { get; init; } = [];
    public ExtractionMetadata Metadata { get; init; } = new();
    public string? ErrorMessage { get; init; }
}

public record ExtractionMetadata
{
    public bool SchemaWasAutoGenerated { get; init; }
    public int LlmCallCount { get; init; }
    public int CorrectionIterations { get; init; }
    public long ProcessingTimeMs { get; init; }
    public int OcrPageCount { get; init; }
}
